### ISSUE TITLE
Dudas de lo basico de la tarea 0

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#13]
Tengo el siguiente problema. No sé como empezar ha hacer la tarea, en el sentido, que una vez clonado el repositorio, no entiendo como hacer para empezar a programar.:
-¿Donde esta el archivo que debo programar?
-Hay un archivo filter.c, pero este ya tiene cosas programadas ¿Que cosas puedo cambiar?
-Me estaba preparando para hacer la tarea desde completamente 0, yo creando todos los archivos en C (más la ayuda de la libreria). Pero ahora veo que me pasan otras ayudas. ¿Que parte de la tarea debo programar yo?
-¿Y en que consiste la makefile? Es que tengo entendido que cada vez que usamos `make`, se crea una nueva makefile, pero aquí es como si nos dieran una de antes con propiedades especiales. Y no entiendo las propiedades, ni el uso que tienen si cada vez que hacemos `make` se crea una nueva.

**Comment by orrios** [comment]
- El archivo que debes programar está en Programa/src/filter/main.c
- Puedes cambiar todo lo que quieras dentro de este archivo pero te recomiendo seguir los tips y hacer los "TODOS" que aprecen comentados en este archivo
- Debes programar el filtro pero con la ayuda de la librería base que entregamos (imagelib). Puedes revisar su codigo en su archivo correspondiente para ver que es lo  que hace, pero no deberías tener que alterarla. Nuevamente, trabajas en main.c
- Con respecto a la makefile, es  una herramienta para la compilación de tu programa que maneja las dependencias y revisa que cosas has cambiado de tu codigo y recompila solo lo necesario (para que así tome menos tiempo la compilación). Tambíen recibe otras instrucciones que utiliza el compilador, como por ejemplo que tan optimizado quieres que esté el ejecutable. En este curso les entregamos el makefile y no tienen que modificarlo salvo colocar la optimización en O3 al momento de entregar la tarea (o ver cuanto se demoraría su algoritmno final).

Recomendación: no partas resolviendo la tarea a ciegas. Trata de entender lo que está pasando y parte trabajando la imagen con cosas sencillas para ver como funciona todo.

**Comment by perojas3** [comment]
Ok, gracias
