### ISSUE TITLE
Sobre Atom

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#2]
Tengo el siguiente problema, el link para instalar Atom en windows me regresa al Home de la wiki. ¿Que hago?

**Comment by negebauer** [comment]
[Google](http://bfy.tw/AU58)

**Comment by negebauer** [comment]
Para complementar
[http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html](http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html)

**Comment by Ghoeb** [comment]
Ahi lo corregí.

**Comment by perojas3** [comment]
Gracias
