### ISSUE TITLE
Memory Leak en imagelib.c

### ISSUE THREAD

**Issue by aaferman** [IIC2133-PUC/2017-1#22]
Hola,

El enunciado de la Tarea 0 dice:
- 10 % a que valgrind indique que no tienes **memory leaks**

Cuando ejecuto valgrind con la opción --leak-check=full
`valgrind --leak-check=full -v ./filter imgs/lena.png tests/blur.txt lenafiltrada2.png`
 me tira un error en la linea 107 de imagelib.c, la librería. El error corresponde a la linea
`img -> pixels = calloc(height, sizeof(Color*));`

Tenemos que hacernos cargo de ese problema? Según valgrind esta relacionado con 
`img -> pixels` y no con img, la cual en el método img_destroy() si libero.

el error:
<img width="877" alt="screen shot 2017-03-20 at 11 16 34 am" src="https://cloud.githubusercontent.com/assets/8892424/24103691/cf0ab9a4-0d5e-11e7-98ae-5adb98499945.png">

Gracias,

Saludos

**Comment by Arios16** [comment]
Sí, tienen que hacerse cargo de liberar toda la memoria, incluyendo la que se pide dentro de `imagelib.c`. Valgrind no debe reportar errores ni memory leaks en su tarea.

> Según valgrind esta relacionado con img -> pixels y no con img, la cual en el método img_destroy() si libero.

No basta con hacer `free(img)`, tienes que liberar los punteros internos del struct Image.

**Comment by aaferman** [comment]
Ok, Gracias!
