### ISSUE TITLE
Still reachable memory leaks

### ISSUE THREAD

**Issue by bmarinb** [IIC2133-PUC/2017-1#24]
![image](https://cloud.githubusercontent.com/assets/17581426/24165211/9636fcd2-0e4e-11e7-92a1-8a40a3812006.png)
En el enunciado de la tarea se indica que valgrind debiera indicar que nuestro programa no tiene memory leaks, sin embargo tengo "still reachable" leaks. 
¿Tengo que preocuparme por eso o está bien?

**Comment by negebauer** [comment]
(No ayudante)

Tienes memoria tomada aún 
Cuando termina tu programa sigues ocupando 568 bytes
Te falta un free (ver línea 3 y 4 del output de Val grind)

**Comment by bmarinb** [comment]
me faltaba el fclose, gracias
