### ISSUE TITLE
Cantidad de tiles

### ISSUE THREAD

**Issue by josemontesp** [IIC2133-PUC/2017-1#26]
Podemos asumir que siempre se va a cumplir que el numero total de tiles a posicionar es igual al ancho * largo? o pueden sobrar tiles?

**Comment by orrios** [comment]
Hola!
Recuerda también que hay espacios inhabitables donde no se pueden colocar tiles. La suma de los espacios inhabitables más todas las piezas a colocar es igual al alto * ancho de la grilla.

**Comment by josemontesp** [comment]
Gracias Oscar!

Este es el easy2.txt son 3x5 espacios, pero hay 12 tiles. Pueden faltar tiles?
```3
5
0
3
2 1 1 1 2
2 3 2 3 6
1 1 3 3 4
```

**Comment by Arios16** [comment]
@josemontesp 

No, no pueden faltar tiles. Hay un error en los tests `easy2.txt` y `easy3.txt`, en #27 puedes encontrar la versión corregida.

**Comment by josemontesp** [comment]
Ah no lo había visto, muchas gracias!


De: Andres Rios <notifications@github.com> <notifications@github.com>
Responder: IIC2133-PUC/2017-1
<reply@reply.github.com>
<reply@reply.github.com>
Filtrar por fecha: 1 de abril de 2017 at 6:50:39 p.m.
Para: IIC2133-PUC/2017-1 <2017-1@noreply.github.com>
<2017-1@noreply.github.com>
CC: Jose Miguel Montes <josemontesp@gmail.com> <josemontesp@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Asunto:  Re: [IIC2133-PUC/2017-1] Cantidad de tiles (#26)

@josemontesp <https://github.com/josemontesp>

No, no pueden faltar tiles. Hay un error en los tests easy2.txt y easy3.txt,
en #27 <https://github.com/IIC2133-PUC/2017-1/issues/27> puedes encontrar
la versión corregida.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/IIC2133-PUC/2017-1/issues/26#issuecomment-290949430>,
or mute the thread
