### ISSUE TITLE
Corrección tests 

### ISSUE THREAD

**Issue by Arios16** [IIC2133-PUC/2017-1#27]
Hay un error en los tests `easy2.txt` y `easy3.txt`. Deberían decir:

`easy2.txt`:

    3
    4
    0
    3
    2 1 1 1 2
    1 3 1 3 6
    1 1 3 3 4

`easy3.txt`:

    4
    4
    0
    5
    2 2 1 1 6
    2 1 2 1 6
    3 2 1 2 2
    3 2 2 1 1
    3 1 2 2 1

Saludos!

**Comment by negebauer** [comment]
Label **IMPORTANTE** ?
