### ISSUE TITLE
Dudas del comienzo

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#29]
Ahora sí, tengo las siguientes dudas.
Primero con la intalacion de GTK 3, en la wiki dice :

> La instalación en Linux Subsystem es equivalente a la de Ubuntu

¿Eso significa que hay que hacer exactamente lo mismo que la instalación de lo de linux, más lo de Windows?

Segundo, es sobre el makefile, en general no entiendo donde debemos programar. El make file crea 2 archivos, el restore y el beholder.  Logro identifica la parte donde están programados, pero no me queda claro. ¿Dónde quieren que programemos? ¿En el main.c del restore?

Yo suelo programar con módulos debido a que es más ordenado, en otras ocasiones suelo poner los módulos .c con sus respectivos .h en el mismo directorio, importar los .h desde los .c que sea necesario. Pero también compilar en conjunto todos los .c. Ahora, con lo que aparece en esta makefile (lo pongo como imagen para evitar problemas de formato):

![la siguiente que poner](https://cloud.githubusercontent.com/assets/14139107/24682696/72c64f22-1971-11e7-9f72-b684885d8c66.jpg)

¿Esto significa que debo poner los .c y .h en una capeta con exactamente el mismo nombre para que se compile?
Ejemplo, estoy haciendo un módulo para leer los archivos .txt, ¿Debería crear una carpeta llamada texto, con los archivos texto.c y texto.h para que la makefile os compile?
Eso seria, muchas gracias.

**Comment by Ghoeb** [comment]
Para responder tu primera pregunta, si, debes hacer lo de Linux y luego hacer lo de Windows.

Para la segunda pregunta, se espera que programen todo dentro de la carpeta "restore", y la Makefile compilará el programa `restore` a partir de la función `main` que encuentre dentro de algún archivo dentro de esa carpeta. Si hay más de una función main dentro de la misma carpeta, la compilación fallará.

Pueden crear todos los .h y .c que quieran, pero no es necesario que se llamen igual para poder compilar, eso ya es un tema de estilo y de orden de uno mismo. (Yo aconsejo que por cada .c haya un .h del mismo nombre que exponga sus funciones y sus structs)

Ojala te sirva mi respuesta :)

**Comment by perojas3** [comment]
Muchas gracias.
Mi tercera pregunta era más respecto donde poner los .h y .c ¿Como y donde pongo las carpetas para que los lea?

**Comment by Ghoeb** [comment]
Si los pones en la misma carpeta "restore" la inclusión se hará de manera automática.

Si quieres crear nuevas carpetas tendrás que hacerlo dentro de la carpeta "restore", y para que la Makefile te las considere, deberás agregarlas a la lista de carpetas "COMMON" definida en la linea 46 de la Makefile. Para que la compilación funcione, además deberás agregarle el flag `-p` al comando `mkdir` en la línea 92.

Por ejemplo, digamos que quieres crear una carpeta para la representación del mapa llamada "map". Esta carpeta debes crearla dentro de "restore", y en la Makefile te queda como sigue:


Linea 46
```bash
COMMON=watcher restore/map
```

Línea 92
```bash
  @mkdir -p $@
```

(Notese que hay un "tab" antes del "@mkdir" en la línea 92. Si usas espacios no va a funcionar)
