### ISSUE TITLE
Sobre como representar el tablero

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#30]
Ahora mismo, para representar el tablero. Estoy usando una matriz (un array de arrays) de los structs que son las casillas, pero quiero que estos son punteros, pero C no me deja hacer:
`struct Casilla***`
Me tira error. ¿Alguno sabe como hacerlo? ¿O mejor me voy por alguna alternativa?

**Comment by Ghoeb** [comment]
¿Qué te tira error? ¿Cual es el mensaje asociado a ese error? ¿Es un error de compilación o de ejecución? Lo que quieres hacer está bien, asi que tu error tiene que estar en como lo escribiste en C.
