### ISSUE TITLE
Generador y Corrector de Tests

### ISSUE THREAD

**Issue by Arios16** [IIC2133-PUC/2017-1#31]
Para que puedan probar bien su tarea 1, dejamos a su disposicion un generador y corrector de tests. Esta disponible para Windows, Linux y macOS de 64 bits.

[windows.zip](https://github.com/IIC2133-PUC/2017-1/files/904394/windows.zip)
[linux.zip](https://github.com/IIC2133-PUC/2017-1/files/904395/linux.zip)
[macOS.zip](https://github.com/IIC2133-PUC/2017-1/files/904397/macOS.zip)

EDIT: actualizado generador, ahora no se cae al crear puzzles con menos de 4 tiles.

Les estamos pasando los binarios ya compilados y no el codigo fuente pues para generar y checkear los puzzles se debe modelar el problema.

Para usarlo, deben descargarse la version correspondiente a su sistema operativo, descomprimirlo, y luego llamar al programa por la linea de comandos con `./gencheck <subcommand>` (puede variar dependiendo de la consola que utilicen). Hay dos subcomandos:

- `gen`: genera un puzzle. Recibe como parámetros (en orden): el path de output, el alto del puzzle, el ancho del puzzle, y opcionalmente el numero de casilleros vacios (por defecto, el numero de casilleros vacios es random). Ejemplos de uso: `./gencheck gen ./test.txt 8 8` genera un puzzle de 8x8 con un numero random de casilleros vacios. `./gencheck gen ./test2.txt 5 5 10` genera un puzzle de 5x5 con 10 casilleros vacios.

- `check`: corrige la solución a un puzzle. Una vez que tengan lista su tarea y sean capaces de generar soluciones a los puzzles, pueden usar este comando para verificar que sus soluciones son correctas. Recibe dos parámetros: el path del archivo de test, y el path del archivo de solucion. Ejemplo: `./gencheck check ./test.txt ./solution.txt`

Preocupense de probar su tarea con puzzles de distintos tamaños, distintas dimensiones y distinto numero de casilleros vacíos de manera de asegurarse que su programa funciona para todos los casos.

Más adelante también se subirán algunos tests clasificados como fáciles/medios/difíciles para que vean lo que se espera de sus programas en terminos de velocidad.

Si tienen algun problema con el generador de tests, pueden preguntar en esta issue.

Saludos!

**Comment by josemontesp** [comment]
Nos pueden adelantar qué se espera en términos de velocidad de nuestro programa?

**Comment by orrios** [comment]
Que sean capaces de resolver los tests de distintas dificultades (que se publicarán en una issue entre hoy y mañana) en menos de 10 segundos.  
Se detallará todo en esa issue.

**Comment by ignaciourzuaf** [comment]
Hola! Estoy trabajando en Linux y ya baje y descomprimí el archivo, pero no puedo usarlo. Al escribir cualquier subcomando me aparece que no se encontró la orden. 
¿Que podrá ser? 

Probé  `sudo ./gencheck check ./easy1.txt ./sol1.txt` (con y sin sudo) y `./gencheck gen ./test2.txt 5 5 10` (con y sin sudo)
Saludos

**Comment by Arios16** [comment]
@ignaciourzuaf 

Cual es exactamente el error que te arroja?

**Comment by ignaciourzuaf** [comment]
Si no uso sudo error -> `bash: ./gencheck: Permiso denegado`,  al usar: `./gencheck ./easy1.txt ./sol1.txt`.

Si uso sudo error -> `./gencheck: orden no encontrada`,  al usar: `sudo ./gencheck ./easy1.txt ./sol1.txt`.

@Arios16, Gracias!

**Comment by Arios16** [comment]
Prueba correr `chmod +x ./gencheck`, y luego correr `./gencheck`

**Comment by ignaciourzuaf** [comment]
Me funcionó, muchas gracias!
