### ISSUE TITLE
Más Tests T1

### ISSUE THREAD

**Issue by orrios** [IIC2133-PUC/2017-1#32]
Estimad@s, acá hay 4 nuevos tests para que prueben su tarea. Deberían ser resolvibles fácilmente en menos de 3 segundos.
* [Test1.txt](https://github.com/IIC2133-PUC/2017-1/files/904409/medium1.txt)
* [Test2.txt](https://github.com/IIC2133-PUC/2017-1/files/904408/medium2.txt)
* [Test3.txt](https://github.com/IIC2133-PUC/2017-1/files/904411/medium3.txt)
* [Test4.txt](https://github.com/IIC2133-PUC/2017-1/files/904410/medium4.txt)

La velocidad de resolución de este tipo de problemas viene dada en gran parte por la cantidad de llamadas realizadas a la función recursiva. El llevar una cuenta de esta cantidad les dará una idea de qué tan rápida es su solución ya que puede ser que estén resolviendo un test muy rápido pero con miles de llamadas recursivas, lo cual no es escalable a problemas más complejos.

Próximamente se subirán tests con un mayor grado de complejidad. Stay tuned.

# Update 
#### TESTS BONUS
Los siguientes tests son de mayor dificultad pero pueden ser resueltos en un tiempo razonable utilizando podas y heurísticas:

* [Hard test 1](https://github.com/IIC2133-PUC/2017-1/files/915325/ghost.txt)
* [Hard test 2](https://github.com/IIC2133-PUC/2017-1/files/915327/invader.txt)
* [Hard test 3](https://github.com/IIC2133-PUC/2017-1/files/915326/pacman.txt)
* [Hard test 4](https://github.com/IIC2133-PUC/2017-1/files/915328/skull.txt)
* [Hard test 5](https://github.com/IIC2133-PUC/2017-1/files/915340/yingyang.txt)

Como referencia, la solución optimizada resuelve cada uno de estos tests en menos de 5 segundos.

**Comment by perojas3** [comment]
Ok, desafio superado. Todos en menos de 1 segundo. ¿Cuando llegan los hard?

**Comment by Ghoeb** [comment]
Durante el fin de semana. Tenemos que implementar la versión optimizada y ver la dificultad de llevar a cabo cada optimización, y luego con eso ver los tests que es capaz de resolver.

**Comment by perojas3** [comment]
Y, ya lo subieron?

**Comment by Ghoeb** [comment]
La solución optimizada ya está, hoy se deberían subir tests lo suficientemente interesantes y dificiles como para el bonus :hourglass_flowing_sand:

**Comment by orrios** [comment]
Se ha editado la issue subiendo los tests tipo bonus.
