### ISSUE TITLE
Problemas con la recursion

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#33]
Tengo el siguiente problema. Todavía no aplico las heurísticas, ni las podas. Se supone que en este estado debería poder hacer los 4 ejercicios easy en menos de 10 segundos. Sin embargo, solo consigo hacer el easy1 en el tiempo pedido.
Desearía que me pidieran (sin aplicar las podas todavía) para acelerar el proceso.
También tengo el problema de que mi programa hace n^n en vez de n! cálculos, debido a que no sé cómo detener un for en C, o cortar un proceso una vez encontrado la solución. De esta forma encuentro 12 veces una solución de easy1, (3 veces cada una de los 4).
¿Qué me pueden recomendar?

**Comment by negebauer** [comment]
Usa `break`

http://stackoverflow.com/questions/1507294/how-to-end-a-loop-early-in-c

**Comment by Ghoeb** [comment]
Hm, como estás buscando la solución al problema? La idea es que lo plantees de manera recursiva, donde pruebas poner una pieza en alguna posición arbitraria y luego llamas recursivamente la funcion resolver con ese estado del problema. Ve como se plantea en la [guia de backtracking](https://github.com/IIC2133-PUC/2017-1/blob/master/Guias/Backtracking.pdf)

**Comment by perojas3** [comment]
@negebauer Muchísimas gracias
@Ghoeb Estaba, por cada espacio vacío, probando con todas las piezas disponibles validas en ese instante (en cada uno de los sentidos), y llamo recursivamente para que se empieza a probar con otro espacio con las piezas que quedan de la misma forma. Y así. Pero (ya lo arreglé) después de que una función deja de intentar con un espacio, empieza de nuevo a intentar con otro. Por lo que de esa forma de vuelven a revisar varias veces las mismas posibilidades. Por ejemplo, en easy1, la primera recursión revisa el primer espacio vacío, la segunda el segundo, y el tercero el tercero. Pero luego cuando termina, el segundo se pone a revisar el tercer espacio, y la tercera recursión se pone a revisar el segundo espacio. De esta forma se revisaba exactamente lo mismo n! veces (donde n es la cantidad de piezas que poner).
Esto lo solucione con lo que me pasaron, y ahora puedo hacer todo en el tiempo adecuado. A demás agregué una poda que me permite hacer en menos de un segundo los mediums.

La pregunta que me queda es. Una vez que encuentro la solución. ¿Hay alguna forma de cortar el programa para evitar que se siga ejecutando?

**Comment by Ghoeb** [comment]
Cuando encuentras solución (o no), retornas. Así es como se hace para terminar la iteración de todos los posibles estados.

Algo asi como 

```c
resolver()
{
  /* ... */
  probar pieza

  if(resolver()) return true;
  
  /* ... */
}

```

**Comment by perojas3** [comment]
Pero mi funcion es void.

**Comment by Ghoeb** [comment]
Has que retorne un bool que indica si logró resolver o no :)

**Comment by perojas3** [comment]
Ok, no tengo idea si lo logro o no, pero lo hice con un int de 0 o 1. Y me sirve.
