### ISSUE TITLE
Recomendaciones para el bonus del informe

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#34]
Me falta escribir el informe, y desearia que me dieran algun consejo para obtener el bonus. ¿Que se nesesita para tener un buen espacio y formato?

**Comment by Ghoeb** [comment]
Que raro, te respondí esto hace 8 hrs y acabo de ver que está sin respuesta.

Te escribo lo que puse antes: El criterio del bonus es subjetivo, pero esto puede servirte como guía:

1. El uso de portada no es necesario, pero sí incluye un título para el informe y sus distintas secciones.
1. Escribir el informe en LaTeX ayuda, pero si eres un mago de Word también sirve :)
1. Evita que una sección sea cortada por el cambio de página.
1. Se formal. Imagina que estas escribiendo un paper, pero que se entienda!
1. Usa notación matemática cuando sea pertinente. Para formulas complejas, trata de dejarlas centradas en su propio espacio (en lugar de tenerlas dentro de un párrafo). 
   * Es importante que sean faciles de leer: prefiere el uso de símbolos y subíndices en lugar de nombres complejos de variables y uso de corchetes. Recuerda explicar que es cada variable.
1. Tu informe debe ser autocontenido. Asume que el ayudante que corrige tu informe no tiene tu código a mano. Si realmente debes comentar algo sobre tu código, incluyelo en tu informe.
1. Respecto a la inclusión de código:
   * Si crees que debes hacer algún comentario respecto al algoritmo, utiliza pseudocódigo como se ha visto en clases
   * Si realmente crees que es necesario incluir código en C por cosas del lenguaje, incluyelo como texto y asegurate de destacarlo con los colores pertinentes (LaTeX tiene paquetes para eso). Si pones una foto de tu código puedes olvidarte del bonus.
1. Para hacer algún análisis estadístico, prefiere totalmente el uso de gráficos en lugar de tablas. Estos deben estar con la leyenda que corresponda.
1. Todo lo externo que incluyas en tu informe (como gráficos o imágenes) debe estar correctamente mencionado en el texto (no como adorno). Estas cosas además deberian ir centradas.

Además, específico para esta tarea: sería ideal que la propuesta de poda y de heurística vinieran detalladas como pseudocódigo, indicando en que parte del algoritmo se aplican.

Saludos :)

**Comment by lhcubillos** [comment]
Hola! Una pregunta... Es posible entregar el informe después del jueves?? Para poder concentrarnos en implementar más podas y heurísticas y así mejorar el programa.

Gracias!

**Comment by Ghoeb** [comment]
No, por eso se llama bonus; la idea es que tengan la tarea lista entera.

**Comment by perojas3** [comment]
¿Cual es la complejidad de un proceso que primero toma n, luego n-1,n-2....1?

**Comment by alopez7** [comment]
la suma de n+n-1+n-2+n-3...+1 es (n-1)n/2, lo que pertenece a O(n^2)
