### ISSUE TITLE
Tiempos comparativos

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2017-1#35]
Para que tengan una idea: La solución de la tarea hace la siguiente cantidad de llamadas a la función recursiva:

* Easy 1: 5
* Easy 2: 75
* Easy 3: 496
* Easy 4: 75
* Medium 1: 6323755
* Medium 2: 3575250
* Medium 3: 760974
* Medium 4: 5589313

**Comment by lhcubillos** [comment]
Y cuanto se demora en cada una?

**Comment by Ghoeb** [comment]
Hm, eso no es un parámetro válido dado que depende del computador... pero si te sirve de algo:

* Easy 1: 0.000041 segundos
* Easy 2: 0.000080 segundos
* Easy 3: 0.000261 segundos
* Easy 4: 0.000090 segundos
* Medium 1: 1.976743 segundos
* Medium 2: 1.122243 segundos
* Medium 3: 0.317310 segundos
* Medium 4: 2.253251 segundos

**Comment by negebauer** [comment]
@Ghoeb y las hard? 🙄
