### ISSUE TITLE
Recorreccion T0

### ISSUE THREAD

**Issue by jicortes2** [IIC2133-PUC/2017-1#38]
Hola! Quería saber como funciona la recorreccion de código de la T0, principalmente, si era posible arreglar algo y recorregir.
Gracias!

**Comment by RodrigoBocazG** [comment]
Y además, hasta cuando podemos recorregir?

**Comment by jgmontoya** [comment]
Aprovecho para preguntar si subirán los tests... ¿subirán los tests?

**Comment by Ghoeb** [comment]
@jicortes2 Respecto a si pueden arreglar algo de su código... identifiquen su error, arreglenlo y veremos si sube o no. Por ser la Tarea 0 seremos flexibles en esto, pero no se acostumbren.

@RodrigoBocazG Tienen dos semanas a partir de la publicación de las notas. 

@jgmontoya Los tests van en camino, serán subidos al repo principal

**Comment by AndresSalcedo** [comment]
Si, porfavor.. tengo todos los puntos hasta el test 4 y de ahí en adelante 0 en todos y no entiendo porqué...

**Comment by perojas3** [comment]
Me recomendaron no usar * para representar multiplicacion. ¿Es mejor ×?

**Comment by alopez7** [comment]
Usa el punto para multiplicar. En latex y en word está el punto
