### ISSUE TITLE
Formato de entrega código

### ISSUE THREAD

**Issue by abannura** [IIC2133-PUC/2017-1#39]
Subimos el código con la parte de la interfaz? O la comentamos? Porque con interfaz corre mas lento. Gracias.

**Comment by Arios16** [comment]
Si la quieres comentar, no hay problema. Si la dejas en el código, nosotros igual cambiaremos la librería por otra que no haga nada al momento de evaluar, de manera de que solo se mida la velocidad de su programa (y no de la interfaz).
