### ISSUE TITLE
Dudas sobre podas

### ISSUE THREAD

**Issue by bmarinb** [IIC2133-PUC/2017-1#40]
¿Se pueden considerar las restricciones implícitas como podas elementales?
¿La simetría de las piezas se puede utilizar como poda?
Esta última pregunta me surgió ya que según la guía de backtracking las podas nos ayudan a eliminar ramificaciones que no van a entregar una solución. Pero en el caso de la simetría lo que se esta eliminando es una ramificación que es exactamente igual a otra, pero que podría ser una solución.

**Comment by btkramm** [comment]
Si esa rama fuese una solución nunca tendrías que haber pensado en girar la pieza, creo.

Saludos.

**Comment by alopez7** [comment]
No se consideran podas eliminar los movimientos que van en contra de las reglas, por ejemplo si pones una pieza conectando un camino con una ciudad. Sí se consideran podas válidas cuando eliminas ramificaciones de la búsqueda que sabes que no te van a llevar a una solución. Si tienes una pieza simétrica y pruebas esta pieza en una posición y no te lleva a la solución, entonces se considera poda cuando no pones la pieza en su posición simétrica.
