### ISSUE TITLE
Complejidad de HeapSort

### ISSUE THREAD

**Issue by btkramm** [IIC2133-PUC/2017-1#42]
El material de clases de Ordenación da como introducción a HeapSort con la oración "Nuestro primer algoritmo O(n) in-place". No sé si estoy olvidando algo pero creo que O(n) era nada más construir el heap, no ordenar mediante HeapSort. Además, HeapSort es O(n log(n)). Pregunto por acá porque no sabía si enviar un correo directo al profesor :D

**Comment by Ghoeb** [comment]
Heapsort es O(n log(n))

Dependiendo como lo hayas visto, construir el heap son
* **n** llamadas a _heap insert_, cada una hace **una** llamada a _sift up_, con un costo de O(log n), para un total de O(n log n)
* **Una** llamada a _heapify_, el cual hace **n** llamadas a _sift down_, cada una con un costo de O(log n), para un total de O(n log n)

Luego obtener los valores son **n** llamadas a _heap extract_, cada una con un costo de O(log n), para un total de O(n log n)

Todo junto queda entonces O(n log n) + O(n log n) = O(n log n)
