### ISSUE TITLE
[Tarea 2] En caso de empate

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2017-1#44]
En el enunciado no esta especificado:

Cuando hay dos o más submelodías que se repiten la misma cantidad de veces (y no hay ninguna submelodía que se repita más veces) entonces se prefiere **la que tenga más notas** de estas.

**Comment by jgmontoya** [comment]
Y si hay dos o más submelodías que se repiten la misma cantidad de veces (y no hay ninguna submelodía que se repita más veces) pero son del mismo largo? ¿Elegimos cualquiera, la que salga primero u ocupamos otro criterio?

**Comment by Ghoeb** [comment]
Creo que use mal el termino. No es la más larga, si no la que tiene mayor cantidad de notas. Si aun así hay empate, entonces cualquiera sirve.
