### ISSUE TITLE
Pueden traslaparse las submelodias?

### ISSUE THREAD

**Issue by eiherrera** [IIC2133-PUC/2017-1#45]
Supongamos que estamos evaluando cuantas veces se repite la melodía `a[1:3]`. Dado que esta se puede repetir en otros semitonos, ¿que pasa si esta se repite en los espacios traslapados `a[4:6]` y `a[5:7]`? ¿Cuento como que se repite 2 veces?

**Comment by Ghoeb** [comment]
Sí.
