### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by panchopp** [IIC2133-PUC/2017-1#46]
Hola, tengo un error con el archivo midilib.c, que al importar smf.h no lo encuentra. Adjunto log del terminal haciendo make (Estoy en mac):

➜  Programa git:(master) make
Package smf was not found in the pkg-config search path.
Perhaps you should add the directory containing `smf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'smf' found
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
src/midimanager/midilib.c:4:10: fatal error: 'smf.h' file not found
#include <smf.h>
         ^
1 error generated.
make: *** [obj/midimanager/midilib.o] Error 1

**Comment by Ghoeb** [comment]
Dime, ¿cual es el output de ejecutar este comando?

```
pkg-config --cflags --libs smf
```

**Comment by panchopp** [comment]
Package smf was not found in the pkg-config search path.
Perhaps you should add the directory containing `smf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'smf' found

**Comment by Ghoeb** [comment]
Solo para confirmar, ¿instalaste **SMF**?

**Comment by panchopp** [comment]
Como se instala?

**Comment by Ghoeb** [comment]
Al final del enunciado de la tarea dice

```
brew install smf
```

Asumo que tienes instalado `brew`, dado que lo usamos para las tareas pasadas

Avisame si te funciona o no

**Comment by panchopp** [comment]
Gracias!, no me había dado cuenta.
