### ISSUE TITLE
[Tarea 2] ¿Subirán tests para poder probar si nuestro output es correcto?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2133-PUC/2017-1#48]

**Comment by Ghoeb** [comment]
Revisaste la carpeta `Programa/audios` de tu repositorio?

**Comment by jgmontoya** [comment]
Sí, pero no hay outputs para contrastar :confused:

**Comment by Ghoeb** [comment]
Lo que pasa es que existen muchos outputs válidos y dependen del `mu`. Durante la semana se subirá un programa que revise si una melodía es solución para el input dado.

**Comment by Ghoeb** [comment]
Revisen #62 😃
