### ISSUE TITLE
[Tarea 2] ¿Pueden haber varios silencios consecutivos?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2133-PUC/2017-1#49]
Es decir, en una submelodía, podría ocurrir que dentro de la secuencia [ ( e_i, t(e_i) ), . . .  , ( e_j, t(e_j) ) ]
exista un k tal que e_k es silencio y e_{k+1} es silencio? 

No especifica en el enunciado pero me da la sensación de que esto no debiera ocurrir porque vendría un solo silencio de duración t(e_k) + t(e_{k+1}).

**Comment by Ghoeb** [comment]
Ajá, por eso mismo eso no debería ocurrir. Si llegara a pasar avisanos porque sería un bug de la librería.

**Comment by jgmontoya** [comment]
Oka, gracias!
