### ISSUE TITLE
Reproducir MIDI en Ubuntu

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2133-PUC/2017-1#50]
Hola no pude reproducir los archivos MIDI en Ubuntu
Me dijeron que descargue Timidity pero lo que encontré en Internet tenía unas instrucciones muy extrañas de descargar.

Es normal eso?  Hay una forma más simple?
Saludos

**Comment by jgmontoya** [comment]
Hola!
Yo instalé timidity haciendo solamente: ```sudo apt-get install timidity timidity-interfaces-extra```
Con eso se instala timidity y una interfaz para usarlo. La interfaz la encontré asquerosamente mala así que terminé usándolo desde el terminal nomás haciendo ```timidity output.mid```

Saludos!

**Comment by KyuubiNoKitsune** [comment]
Muchas gracias!
Ahora, intento reproducir el archivo que descargué con Timidity pero es super raro el programa.  Pone file load pero no me deja añadirlo.
¿Sabes cómo se hace?

**Comment by KyuubiNoKitsune** [comment]
Ah verdad que dijiste que la interfaz era asquerosa ... tienes razón, probaré el comando en terminal.

**Comment by KyuubiNoKitsune** [comment]
funcionaaa!!! gracias te pasaste :D!!!
