### ISSUE TITLE
¿La restricción de largo incluye los silencios o solo las notas?

### ISSUE THREAD

**Issue by javierlopeza** [IIC2133-PUC/2017-1#51]
Por ejemplo, si **mu = 3** ¿el alma puede ser una melodía con dos notas y un silencio entre ellas? ¿O **mu** representa el número de notas sin contar silencios?

**Comment by Ghoeb** [comment]
b) **mu** representa el número de notas sin contar silencios.

**Comment by jgmontoya** [comment]
Creo que esto debiera tener tag de importante porque del enunciado se deduce algo distinto: 

![image](https://cloud.githubusercontent.com/assets/11434422/25643514/aa80e5b0-2f76-11e7-8f8a-0042198472e3.png)
![image](https://cloud.githubusercontent.com/assets/11434422/25643567/e73fa306-2f76-11e7-8217-0797bf252e13.png)

**Comment by Ghoeb** [comment]
@jgmontoya Toda la razón. Muchas gracias.
