### ISSUE TITLE
[Tarea 2] ¿Donde programamos el programa?

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#53]
Como en las 2 tareas anteriores tengo la duda. ¿En que archivo programamos el programa?
Porque me parece que hay 2 lugares donde podriamos programarlo, en distill y midimanager.
Me da la imprecion que es distill porque tiene TODOs, pero entonces. ¿Para que esta midimanager?

A demas, quiero saber. ¿Hay restricciones para modular como en la tarea anterior?

**Comment by Ghoeb** [comment]
Tu programa es `distill`, por lo que debes programar dentro de esa carpeta.

La Makefile está actualizada, por lo que ahora puedes crear carpetas dentro de la carpeta distill, pero debes agregarlas nuevamente a la variable `COMMON` de la Makefile.

**Comment by perojas3** [comment]
Ok. Entonces ignoramos midimanager. ¿Verdad?

**Comment by Ghoeb** [comment]
Si, el midimanager es llamado internamente por midi.c

Está separado del programa dado que depende de una librería que es incompatible con valgrind: si estuviera dentro de tu programa no podrías debugear correctamente tu tarea.
