### ISSUE TITLE
Silencios seguidos

### ISSUE THREAD

**Issue by lhcubillos** [IIC2133-PUC/2017-1#54]
Hola, podemos asumir que la canción entregada no partirá con un silencio, y que no tendrá dos silencios seguidos?

Gracias!

**Comment by jgmontoya** [comment]
Según explicaron en #49 no debieran haber dos silencios seguidos. Lo otro no lo sé.

**Comment by Ghoeb** [comment]
Lo otro no debería pasar.

**Comment by javierlopeza** [comment]
¿Y podría terminar con un silencio?

**Comment by rkoco** [comment]
No debería pasar. La conversión midi > melody maneja eso.
Sin embargo si van a trabajar con midi (Múltiples capas) ya no se podría asegurar.
