### ISSUE TITLE
Cantidad de notas

### ISSUE THREAD

**Issue by abannura** [IIC2133-PUC/2017-1#55]
Cual es el numero máximo que podrá tener una nota? Para saber si conviene o no usar counting sort, y cual es el valor de k para ese algoritmo. Gracias.

**Comment by Ghoeb** [comment]
En midi las notas van de 0 a 127.

**Comment by abannura** [comment]
Dale gracias! Y el largo de una melodia en general sera mayor que 128?

**Comment by Ghoeb** [comment]
No puedes asumir nada sobre el largo de una melodía, excepto que cabe en tu computador :)

(Igual los tests son musica de verdad, la cual en general tiene un largo acotado: no vamos a generar cosas feas arbitrariamente largas solo para probar que tu tarea funciona)

**Comment by Ghoeb** [comment]
DISCLAIMER: Solo vamos a generar tests suficientemente largos para ver que no la resolviste utilizando fuerza bruta.
