### ISSUE TITLE
Segmentation fault en OSX

### ISSUE THREAD

**Issue by abannura** [IIC2133-PUC/2017-1#56]
Estoy con un seg fault cuando corro mi programa en Mac, pero no ocurre cuando corro en linux. Poniendo prints, creo haber determinado que el seg fault se produce en la función melody_to_midi (no puedo probar con valgrind porque no esta para OSX). El problema no ocurre en toda ejecución, pero en general sí. Existe la posibilidad de que el seg fault sea de dicha función (quizás no fue hecha para OSX), o si o si es algo de mi código? Muchas gracias de antemano.

**Comment by Ghoeb** [comment]
Y no usaste valgrind en linux para saber donde se cae?

**Comment by famaranon** [comment]
@abannura cual era el problema ? a mi me pasa lo mismo.
