### ISSUE TITLE
¿Como fuciona lo de los semitonos?

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#57]
No entendi lo que decia en el enunciado. ¿Porque menciona los semitonos? ¿Acaso se puede dar la posibilidad de que un alma no se halla repetido de la misma forma durante la melodia?

**Comment by Ghoeb** [comment]
No solo la posibilidad, es certero: debes buscar submelodías que tengan las mismas diferencias entre notas, no las mismas notas.

**Comment by perojas3** [comment]
OK, en ese caso, ¿Que verción de el alma debemos entregar?

**Comment by Ghoeb** [comment]
Cualquiera sirve, mientras cumpla las condiciones :)
