### ISSUE TITLE
¿Existencia de notas bemoles y sostenidas?

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2133-PUC/2017-1#58]
En el ejemplo y en la tarea no veo la existencia de estas notas en las melodías.  Si éstas existen la cantidad de combinaciones sería alta.

Quiero saber si considero solamente las notas DO RE MI FA SOL LA SI o si también considero la existencia de notas como, FA sostenido y SI bemol.

Mi otra duda es que si importa también la agudez de la nota (o frecuencia) ya que no es lo mismo la del Do central con la de una escala mayor.  Me tinca que las melodías de los tests no tienen siempre las notas con la misma frecuencia.

**Comment by Ghoeb** [comment]
Existen, por supuesto. Las notas vienen enumeradas por semitonos, eso incluye entonces bemoles y sostenidos. No aparecen en los ejemplos del enunciado para no complicarlos con símbolos extra.

Efectivamente la nota misma no importa, solo importa la diferencia en semitonos de una nota con la siguiente, dado que de eso depende que dos melodías sean iguales.

**Comment by KyuubiNoKitsune** [comment]
Muchas gracias!
