### ISSUE TITLE
T0 imagelib.h 404

### ISSUE THREAD

**Issue by josemontesp** [IIC2133-PUC/2017-1#6]
No encuentro la librería para manejar imágenes. Además el enunciado habla de que tengo que trabajar en mi repositorio. Me creo uno? o me van a asignar uno?

**Comment by alopez7** [comment]
En unos minutos les damos sus repositorios. Ahí está el código base con la librería de imágenes incluida

**Comment by orrios** [comment]
Ya están todos los repositorios creados.
Saludos!
