### ISSUE TITLE
Error al importar melody.h

### ISSUE THREAD

**Issue by FranLucchini** [IIC2133-PUC/2017-1#60]
Hola,

Ahora que se supone que funciona el linter, tengo otro problema misterioso. Traté de crear una carpeta dentro de distill para hacer operaciones del suffix array, no reconoce el tipo Melody a pesar de que lo importé correctamente. Le pregunté a una amiga cómo importó la librería y lo hizo igual que yo, por eso no entiendo porqué el mio no funciona.

Ojalá alguien me pueda ayudar.

**Comment by Ghoeb** [comment]
¿Puedes poner el código de como lo estás importando? Además de el árbol de tus archivos.

**Comment by Ghoeb** [comment]
Also, independiente de lo que diga el linter... compila correctamente?

**Comment by FranLucchini** [comment]
No compila, manda el mismo error.
Dentro de el archivo `src/distill/sorting/sorting.h` tengo esto importado:
```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../../music/melody.h"
```

Dentro de el archivo `src/distill/sorting/sorting.c` tengo esto importado:
```C
#include "sorting.h"
```

**Comment by Ghoeb** [comment]
Pucha, no se que puede ser. Por ahora, puedes poner todos los archivos en src/distill y te va a funcionar igual, ok? 😄

**Comment by FranLucchini** [comment]
Se arregló misteriosamente cuando borré las cosas y las importé de nuevo xD
