### ISSUE TITLE
Duración de elementos

### ISSUE THREAD

**Issue by famaranon** [IIC2133-PUC/2017-1#63]
La duración de los elementos en los archivos de audio son números enteros que en algunos casos tienen valores atípicos que no se repiten en la partitura. ¿ Esto es correcto o la duración debería tener valores como los que salen en el enunciado (1 - 2) ?

**Comment by Ghoeb** [comment]
Eso es completamente normal. No todos los elementos aparecen repetidos, y la relación MIDI - Partitura no es 1:1, aunque se asemeja bastante (en general midi crea silencios entre notas, y su largo depende del instrumento). 

Pero esos valores son tal que no afectan la consistencia del problema, por lo que debes preocuparte nada más de que sean los mismos.
