### ISSUE TITLE
Ultima nota y signo de la diferencia

### ISSUE THREAD

**Issue by abannura** [IIC2133-PUC/2017-1#65]
Dos dudas: 
La diferencia de la ultima nota la definimos como 0?
Se considera el valor absoluto de la diferencia con la siguiente nota?
Gracias.

**Comment by abannura** [comment]
Otra duda sobre un test: en saria.mid (easy), cuando usamos mu=2, la sub melodía que más se repite se repite 4 veces o no? Porque en el nombre del archivo del output esperado sale que es 3:

<img width="854" alt="screen shot 2017-05-09 at 6 16 27 pm" src="https://cloud.githubusercontent.com/assets/20782578/25873414/d5af6d60-34e4-11e7-8ef2-b2aead4cf50d.png">

O quizás hay algo que no estoy entendiendo bien. Gracias!

**Comment by Ghoeb** [comment]
Respecto a tu primera duda, como resolver el caso de los extremos de la melodía es algo que se te tiene que ocurrir a ti.

Respecto a tu segunda duda...es más sutil que eso, y tiene que ver con la disposición de las notas:

Los primeros 3 pares de notas que marcaste son todos un salto de **Fa** a **La**, el cual es de 4 semitonos.

El último, en cambio, es un salto de **Mi** a **Sol**, el cual es de 3 semitonos.

La intención de las partituras es más que nada ayudarlos a hacerse una idea visual de la melodía (en especial respecto a las duraciones) pero no deberian usarlas como guia para los saltos entre notas si no saben leerlas.

Saludos!

**Comment by abannura** [comment]
Dale gracias!
