### ISSUE TITLE
Metadata elementos melodía

### ISSUE THREAD

**Issue by javierlopeza** [IIC2133-PUC/2017-1#67]
La estructura `musical_element` tiene `metadata`: ¿en qué se ve reflejado eso al escucharla? Por lo que vi `metadata` es un arreglo de 2 enteros, ¿qué significa cada uno? ¿puede ser que tenga que ver con los instrumentos + silencios/bemoles/etc? Pregunto para saber qué valores tenemos que poner como metadata en cada elemento (al exportar el midi "alma"). Gracias!

**Comment by Ghoeb** [comment]
La idea es que simplemente recorten la melodía original y generen un MIDI con eso, sin tocar la metadata.

La metadata dicta el instrumento y la intensidad de la nota.

(Los silencios estan en otra parte, y los bemoles son parte del sistema enumerado de notas)

**Comment by javierlopeza** [comment]
Ok, gracias!
