### ISSUE TITLE
Resultados output

### ISSUE THREAD

**Issue by jedelacarrera** [IIC2133-PUC/2017-1#68]
En los output encuentro que no todas las veces están correctos, por ejemplo en este caso que es el de easy/bolero-of-fire con mu=2, dice que la melodía que más se repite tiene 2 notas y se encuentra 9 veces en la melodía, siendo que según mi parecer aparece 10. ¿Hay algún factor que no estoy tomando? 

En la foto están seleccionadas 10 veces que se repiten melodías de 2 notas con 3 unidades de diferencia pero en output dice que son 9.

![screenshot from 2017-05-13 14-43-04](https://cloud.githubusercontent.com/assets/17602641/26029132/06ca648c-3804-11e7-9c43-ba5d4173aad3.png)

**Comment by jmcomber** [comment]
El 23 tiene length 2560, así que no cuenta

**Comment by Ghoeb** [comment]
Lo que dice tu compañero :)
