### ISSUE TITLE
Recorrección Tarea 1 + Tests Usados en la Correccion

### ISSUE THREAD

**Issue by Arios16** [IIC2133-PUC/2017-1#70]
En la carpeta de la Tarea 1 [(acá)](https://github.com/IIC2133-PUC/2017-1/tree/master/Tareas/Tarea%201/Tests%20usados%20en%20la%20correccion) pueden encontrar los tests utilizados en la correccion de esta tarea.

La política para la recorrección es igual que en la tarea 0: Si quieren recorregir su código o informe, abran una issue en su repositorio de la tarea. Si quieren recorregir ambos, haganlo en dos issues distintas. 

Se permitirá cambios de código en la recorrección, pero aplicando un descuento de 4 décimas por statement cambiado/agregado/eliminado.

Saludos!

**Comment by bmarinb** [comment]
Andrés, yo tuve un problema un poco diferente.
En todos los test de ejemplo las tiles iban en orden
0,0
0,1
1,0 etc
En los test que usaron para corregir no lo hicieron así y por eso mi programa se cae (claramente me fue muy mal por culpa de eso)
Para arreglar eso tengo que cambiar un número no menor de líneas, pero mi error fue solo 1 y muy puntual. ¿Pueden hacer una excepción para este error y por ej, que se haga un descuento fijo en vez de 4 décimas por statement?

**Comment by jfcumsille** [comment]
Tengo el mismo problema, reordene los tiles en los test de corrección y me corren perfecto. Hay algo que se pueda hacer?

**Comment by matusfelipe** [comment]
Me sumo al problema ¿Es posible realizar una re-corrección sin modificar el código, pero con los archivos de test re-ordenando las celdas deshabitadas de menor a mayor?

**Comment by Arios16** [comment]
Para los que asumieron que las celdas de solo pasto venian en orden, les vamos a permitir arreglar ese problema por un descuento fijo de 1 punto. Corrijan su código, abran una issue en su repo y digan que estan corrigiendo este problema para que lo tomemos en cuenta.

**Comment by bmarinb** [comment]
El descuento es solo sobre la nota de código cierto?

**Comment by Arios16** [comment]
Sí, el descuento por cambiar el código en la recorrección es solo sobre la nota de código.
