### ISSUE TITLE
Resultado de tests

### ISSUE THREAD

**Issue by bregonesi** [IIC2133-PUC/2017-1#71]
En el enunciado nos dicen que las submelodías no pueden empezar ni terminar con silencios, sin embargo, en el test `mu 6 notas 6 veces 2.mid` la melodía termina con silencio.

<img width="925" alt="screen shot 2017-05-16 at 17 34 30" src="https://cloud.githubusercontent.com/assets/14252577/26130272/e1590c8e-3a61-11e7-91eb-f5f0317b5726.png">

<img width="801" alt="screen shot 2017-05-16 at 17 34 41" src="https://cloud.githubusercontent.com/assets/14252577/26130351/4c3a9fea-3a62-11e7-8e2c-9d956935a163.png">

Que hacemos en estos casos?

**Comment by Ghoeb** [comment]
Eso es padding agregado por la librería de MIDI, la melodía solución tiene 3 notas, 1 silencio y 3 notas. No hay nada especial que hacer en "estos casos".
