### ISSUE TITLE
¿Como manipulo el struct melody de manera adecuada?

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#72]
Tengo el siguiente problema. Ya logre identificar la el "sub array" del array "element_array" del struct melodi que corresponde al alma de la melodia. Sin embargo, soy incapaz de manipularlo sin que me salga el siguiente error:
`*** Error in './distill': free(): corrupted unsorted chunks: 0x00000000015f6ec0 ***`
Mi siquiera lo evito cuando cambio el `melody->length` y luego lo vuelvo a colocar en el valor anterior.
¿Porque me ocurre este error, y como evito que me pase?
Pues ya estoy basicamente terminando la tarea.

**Comment by josemontesp** [comment]
Tuve un error similar que ocurria al copiar la metadata por referencia para crear el alma, entonces al hacer free de la melodía, indirectamente liberaba la memoria del metadata del alma, y me tiraba error al hacer free en alma, ya que la metadata ya estaba liberada. 

Espero que te ayude :)

Jose Miguel Montes

**Comment by Ghoeb** [comment]
Lo que se puede hacer es obtener el indice donde comienza el alma y la cantidad de elementos que tiene, y a partir de eso construir una referencia al alma sin tener que solicitar memoria nueva ( y por ende, sin tener que liberarla)

```C
Melody* melody;
int soul_index;
int soul_length;

Melody soul;

soul.length = soul_length;
// Tomamos el puntero de la dirección de memoria donde comienza el alma
soul.element_array = &(melody -> element_array[soul_index]);

midi_to_file(melody_to_midi(&soul), argv[3]);
```

Luego se libera "melody" como siempre, pero no hay que liberar nada de "soul"
