### ISSUE TITLE
Escalas distintas

### ISSUE THREAD

**Issue by gemoraga** [IIC2133-PUC/2017-1#73]
Hola,
no me queda claro el caso en que el alma tiene submelodías que están en escalas distintas, ¿Cuál hay que entregar como output? Digo porque en algunos casos mi programa devuelve una melodía equivalente a los outputs de prueba que subieron, pero en una escala distinta.
Gracias.

**Comment by negebauer** [comment]
#61 #57

**Comment by gemoraga** [comment]
Gracias.
