### ISSUE TITLE
Error en test de Requiem of Spirit

### ISSUE THREAD

**Issue by FranLucchini** [IIC2133-PUC/2017-1#74]
Saludos,

Creo que el test mencionado en el título de la issue es la melodía completa. Sólo para confirmar, repite la misma submelodía 3 veces, o no?

**Comment by Ghoeb** [comment]
Ah, si, eso es un error. Efectivamente es la misma melodía de 6 notas 3 veces.

**Comment by alopez7** [comment]
[mu 6 notas 6 veces 3.mid.zip](https://github.com/IIC2133-PUC/2017-1/files/1006306/mu.6.notas.6.veces.3.mid.zip) Aquí está el correcto
