### ISSUE TITLE
[Tarea 2] Nota asociada a silencios

### ISSUE THREAD

**Issue by jgmontoya** [IIC2133-PUC/2017-1#75]
Hola,

Quería saber si es correcto asumir que la librería que nos entrega la melodía ya entrega el valor correcto como nota de los silencios o si no debemos confiarnos del valor como nota que entrega y debemos calcularlo nosotros.

![image](https://cloud.githubusercontent.com/assets/11434422/26160800/3a1d4e96-3af0-11e7-9d3d-cb4b9a2d41f2.png)

Saludos!

**Comment by negebauer** [comment]
Tengo entendido que tenemos que calcularlo

**Comment by KyuubiNoKitsune** [comment]
Hay que calcularlo! Asumiendo que su número es el de la nota anterior a éste.  Asumo que ninguna melodía que nos darán comienza con silencio.

**Comment by jgmontoya** [comment]
@IIC2133-PUC/ayudantes pls confirm?

**Comment by rkoco** [comment]
Calculalo, no lo puedes asumir

**Comment by jgmontoya** [comment]
Entendido.

Solo por curiosidad, ¿A qué corresponde el valor como nota que ya viene en los silencios?

**Comment by negebauer** [comment]
Placeholder? :eyes:

**Comment by jgmontoya** [comment]
Que raro, quizás usarán otra librería?? :roll_eyes: 

![image](https://cloud.githubusercontent.com/assets/11434422/26172695/4c546b72-3b17-11e7-9a2f-17b56179e3ad.png)

**Comment by negebauer** [comment]
Lo ponen y nos hacen calcularlo igual 😮

**Comment by Ghoeb** [comment]
Yo lo puse por si acaso :D

**Comment by jgmontoya** [comment]
@Ghoeb entonces lo calculamos o no???

**Comment by negebauer** [comment]
@jgmontoya si hay que calcularlo igual 😕
