### ISSUE TITLE
[Tarea2] Problema con leaks de memoria

### ISSUE THREAD

**Issue by perojas3** [IIC2133-PUC/2017-1#76]
Tengo el siguiente problema con valgrind. Primero, nunca termina, se queda pegado.
Y luego, me dice (incluso cuando no hago nada más que lo que ya venia) que hay leaks en el archivo midi.c
¿Que pasa, y que deberia hacer?

**Comment by jmcomber** [comment]
a mí me pasa lo mismo, lo hablamos en #69 
Yo lo que hice fue correr valgrind en una máquina virtual de Ubuntu, en vez de Windows y ahí me funcionó bien valgrind. Eso sí sigo sin saber por qué pasa.
