### ISSUE TITLE
Posible error en prelude-of-light

### ISSUE THREAD

**Issue by bmarinb** [IIC2133-PUC/2017-1#77]
Los 2 primeros compases debiesen ser el alma, ya que son 7 notas y se repite 2 veces.  Estoy considerando las 2 notas ligadas por separado, ya que así vienen en el element_array.
![image](https://cloud.githubusercontent.com/assets/17581426/26168956/04e20202-3b0a-11e7-8d94-71e417f626fd.png)

**Comment by jgmontoya** [comment]
pero hay una que se repite 3 veces
