### ISSUE TITLE
Notas faltantes al principio

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2133-PUC/2017-1#78]
Quería saber si alguien tuvo un error de este tipo y lo solucionó.

Es ese patrón el que se me cumple y está super difícil de detectar.

Saludos

**Comment by jgmontoya** [comment]
No entendí el error

**Comment by KyuubiNoKitsune** [comment]
Como que las melodías salen iguales en casi todas a las de los ayudantes pero del principio les faltan 3 notas ( a veces 1).

**Comment by jgmontoya** [comment]
Ah pucha a mi no me pasa

**Comment by KyuubiNoKitsune** [comment]
gracias de todas formas :)
