### ISSUE TITLE
Duda informe

### ISSUE THREAD

**Issue by gemoraga** [IIC2133-PUC/2017-1#79]
La segunda parte del análisis pedido dice que describamos las modificaciones que realizamos a la estructura de datos. No entiendo a qué estructura de datos se refieren.

**Comment by FranLucchini** [comment]
Supongo que se refiere al Suffix Array y la LCP, o no?
Yo me imagino que puedes describir cómo los usaste y si añadiste algo extra.

**Comment by gemoraga** [comment]
Gracias.
