### ISSUE TITLE
Operation y número de bits

### ISSUE THREAD

**Issue by afcerna** [IIC2133-PUC/2017-1#80]
Por lo que entiendo Operation es solo un uint8_t, si los primeros 2 bits deciden que moviemiento es y los siguientes 6 bits definen el indice donde se aplica el movimiento.
¿Si existe entonces un limite dado por 3 bits para cada indice (de columnas y filas), es m,n<=8?
Si lo he entendido mal, me pueden explicar que significan los bits de Operation? gracias

**Comment by Ghoeb** [comment]
No, los límites de m y n (numero de filas y columnas) es 64, es decir, estos usan como máximo 6 bits.

La restricción de 0 <= x < 8 es para los valores de cada celda de la matriz, esos efectivamente nunca van a usar más de 3 bits. Es decir, `puzzle -> matrix[r][c] < 8` siempre, con `0 <= r < m, 0 <= c < n`

No es necesario que entiendas la codificación interna de Operation, para eso están las funciones al final de `operation.h` que te dan el tipo de operación y el indice sobre el cual se efectúan.

```C
/** Obtiene la dirección de la operación: 'L', 'R', 'U' o 'D' */
char       operation_direction    (Operation op);

/** Obtiene el índice sobre el cual se efectúa la operación */
uint8_t    operation_index        (Operation op);
```

`'L'` y `'R'` son un movimiento de fila, por lo que index implica sobre cual fila se hace el movimiento
`'U'` y `'D'` son un movimiento de columna, por lo que index implica sobre cual columna se hace el movimiento
