### ISSUE TITLE
Problema al importar la libreria GMP

### ISSUE THREAD

**Issue by panchopp** [IIC2133-PUC/2017-1#81]
Hola, cuando hago make, me sale lo siguiente:

ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [beholder] Error 1

Esto después de que me aparecía lo mismo con la librería png, pero que solucioné modificando el makefile con un comando que @Arios16 publico para la librería png en la tarea 0, este código era:
-I/usr/local/Cellar/libpng/1.6.28/include -L/usr/local/Cellar/libpng/1.6.28/lib

**Comment by Ghoeb** [comment]
Si ya tienes GMP instalado, entonces busca en esa misma carpeta `/usr/local/Cellar/` los archivos de GMP para incluirlos tal como incluiste PNG.

Avisame como te va (no tengo Mac así que no puedo asegurarte que funcione)

**Comment by panchopp** [comment]
Hice lo mismo para el GMP, pero sigo teniendo un error:

el makefile se ve asi ahora:

# Matemáticas (C Math library)
MTH=-lm
# Interfaz gráfica GTK+
GTK=`pkg-config --cflags --libs gtk+-3.0`
# Manejo de imagenes PNG (Portable Network Graphics)
PNG= -I/usr/local/Cellar/libpng/1.6.29/include -L/usr/local/Cellar/libpng/1.6.29/lib
# Manejo de numeros arbitrariamente grandes: GNU Multi Precision library (GMP)
GMP= -I/usr/local/Cellar/libgmp/6.1.2/include -L/usr/local/Cellar/libgmp/6.1.2/lib

y me arroja el siguiente error:

ld: warning: directory not found for option '-L/usr/local/Cellar/libgmp/6.1.2/lib'
Undefined symbols for architecture x86_64:
  "_png_create_info_struct", referenced from:
      _img_png_read_from_file in imagelib.o
      _img_png_write_to_file in imagelib.o
  "_png_create_read_struct", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_create_write_struct", referenced from:
      _img_png_write_to_file in imagelib.o
  "_png_destroy_read_struct", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_destroy_write_struct", referenced from:
      _img_png_write_to_file in imagelib.o
  "_png_get_bit_depth", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_get_color_type", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_get_image_height", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_get_image_width", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_get_valid", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_init_io", referenced from:
      _img_png_read_from_file in imagelib.o
      _img_png_write_to_file in imagelib.o
  "_png_read_image", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_read_info", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_read_update_info", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_set_IHDR", referenced from:
      _img_png_write_to_file in imagelib.o
  "_png_set_expand_gray_1_2_4_to_8", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_set_filler", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_set_gray_to_rgb", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_set_longjmp_fn", referenced from:
      _img_png_read_from_file in imagelib.o
      _img_png_write_to_file in imagelib.o
  "_png_set_palette_to_rgb", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_set_strip_16", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_set_tRNS_to_alpha", referenced from:
      _img_png_read_from_file in imagelib.o
  "_png_write_end", referenced from:
      _img_png_write_to_file in imagelib.o
  "_png_write_image", referenced from:
      _img_png_write_to_file in imagelib.o
  "_png_write_info", referenced from:
      _img_png_write_to_file in imagelib.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [generator] Error 1

**Comment by Ghoeb** [comment]
Que pasa si eliminas el `-L/usr/local/Cellar/libgmp/6.1.2/lib` ?

**Comment by panchopp** [comment]
Elimine libpng que esta produciendo error y gmp, pero sigo teniendo el mismo problema, ahora deje el makefile como el original.
Obtengo el siguiente error:

ld: library not found for -lpng
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [beholder] Error 1

**Comment by Ghoeb** [comment]
Ya, borra el `-lpng` de la Makefile.

**Comment by panchopp** [comment]
Deje comentado el -lpng. Ahora me tira este error:

compiled 'obj/random/pcg_basic.o'
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [beholder] Error 1

**Comment by Ghoeb** [comment]
Confirmemos algo. Instalaste GMP, cierto?

Invoco a @cotehidalgov para soporte en Mac

**Comment by panchopp** [comment]
Si. osea hice brew install gmp

**Comment by Ghoeb** [comment]
Crees que puedas pasar por el DCC hoy tipo 17:00?

**Comment by panchopp** [comment]
No creo que pueda tan tarde, podría ser ahora en almuerzo o a las 3:30?

**Comment by Ghoeb** [comment]
Al menos yo me desocupo a las 17:00 😞

**Comment by panchopp** [comment]
:/ ¿Qué mas podemos hacer?

**Comment by cotehidalgov** [comment]
Ven al cai ahora si quieres para ver que onda.

**Comment by Ghoeb** [comment]
Si ya lo resolviste, sería bueno que pusieras como por si alguien tiene el mismo problema. Si no, voy a estar en el DCC de 16:30 a 18:30 hrs :)

**Comment by panchopp** [comment]
Si! ya lo resolvi. @cotehidalgov  me ayudo, terminé actualizando Xcode y la linea de comandos de Xcode y ahi me pesco todas las librerías.
Muchas gracias a los dos!

**Comment by perojas3** [comment]
Yo tengo el mismo problema.
¿Como se arregla?

**Comment by Ghoeb** [comment]
@perojas3 hasta donde entiendo, estás trabajando en windows, no? Que te apareció en la consola al escribir

```bash
sudo apt-get install libgmp-dev
```

?
