### ISSUE TITLE
Duda Hashing Perfecto

### ISSUE THREAD

**Issue by raiperez** [IIC2133-PUC/2017-1#82]
Hola.

El tablero tiene una cantidad de estados posibles igual a 8^(64*64). 
Si deseamos entonces mappear cada estado a un único valor y viceversa, entonces necesitaríamos una tabla de hash de ese mismo tamaño, lo que suena poco factible. ¿Cómo implementamos entonces la tabla de hash? 

Pensaría en aplicarle módulo al resultado de la función de hash perfecta, pero esto generaría que la función de hash completa (incluyendo la operación módulo) sí encuentre colisiones, cuando el enunciado dice explícitamente que necesitamos una función inyectiva.

Saludos

**Comment by alopez7** [comment]
No es conveniente crear la tabla con un tamaño fijo ya que a pesar de que existen muchos posibles estados, el programa explorará una ínfima parte de estos. Es por esto que es mejor hacer el tamaño de la tabla de manera dinámica.
La función de hash perfecta debe ser inyectiva, esto no quiere decir que no hayan colisiones. La posición del dato en la tabla si usas el método del módulo es h(state)%size.

**Comment by Ghoeb** [comment]
Creo que estás confundiendo el hash de un objeto y el índice de la tabla en el que cae. 

El hash de un objeto `x` usando la función de hash `h`, también conocido como `h(x)`, es un número tal que `x = y -> h(x) = h(y)`. Idealmente, `h` se construye de manera de aprovechar toda la información de un `x` dado, para minimizar la probalididad de colisiones.

Una tabla de hash `T` de tamaño `m` que usa una función de hash `h` decide (en principio) guardar `x` en `T[h(x) % m]`, dado que debe dejar `x` dentro de `T` aunque `h(x) > m`. Notese que aunque `x` se guarde en `T[h(x) % m]`, el `h(x)` no cambia. 

Una función de hash se dice perfecta cuando cumple que `x = y <-> h(x) = h(y)`

> Pensaría en aplicarle módulo al resultado de la función de hash perfecta, pero esto generaría que la función de hash completa (incluyendo la operación módulo) sí encuentre colisiones, cuando el enunciado dice explícitamente que necesitamos una función inyectiva.

Aplicarle módulo al valor de la función no cambia el valor de la función en sí. Una función de hash es **independiente** de la tabla que la usa (en especial del tamaño de la tabla)

> El tablero tiene una cantidad de estados posibles igual a 8^(64*64).

No, el tablero tiene una cantidad de estados posibles **menor o igual** a 8^(height*width). El caso que tu pones es el del tablero más grande posible.

> Si deseamos entonces mappear cada estado a un único valor y viceversa

Cada estado se mapea a un único valor, y dos estados distintos necesariamente mapean a valores distintos, pero eso no significa que cada valor sea un estado.



Dependiendo la relación entre `h` y `m`, usar módulo para ver donde se guarda un elemento podría no distribuir bien. Es por eso que existen correcciones a eso, como el **Método de la multiplicación** y **Hash universal**, pero para esta tarea se espera que usen módulo nomás. (lo otro es parte del bonus)

**Comment by raiperez** [comment]
Perfecto! Me quedó clarísimo, muchas gracias!
