### ISSUE TITLE
Duda Hashing incremental

### ISSUE THREAD

**Issue by mglambert** [IIC2133-PUC/2017-1#83]
No entiendo en que consiste una función de hashing incremental, he buscado pero no he encontrado una buena descripción de que es y como debiese funcionar.

Saludos.

**Comment by alopez7** [comment]
Un Hash incremental es aquel que se puede calcular a partir de un hash anterior. Por ejemplo, si hasheo un string "abcde" como la suma de sus valores ASCII y me da h1 = H("abcde"), puedo calcular facilmente el hash de otro string "abzde" a partir de h1.
Para eso le resto a h1 el valor ASCII de "c", y le sumo el valor ASCII de "z".
De esta manera me ahorro tener que calcular el hash del string completo.
Ahora digamos que las operaciones válidas sobre strings son:

* Change(i,c): cambia el caracter en la posicion "i" del string por el caracter "c".
* Pop(i): Elimina el caracter en la posicion "i" del string.
* Insert(i, c): inserta el caracter "c" en la posicion "i" del string.

Dadas estas operaciones, se puede calcular el Hash de un string dada una operacion y un estado anterior de la siguiente forma: Supongamos que el estado anterior es "abcdfeneurwghrerbtgeu" y su hash es 8757 (numero inventado).

* Si hago Change(2, "k") por ejemplo, el hash nuevo es 8757 - ASCII("c") + ASCII("k"), ya que remplazo la letra "c" de la segunda posicion por una "k".

* Si hago Pop(5) por ejemplo, el hash nuevo es 8757 - ASCII("e"), ya que elimino la "e" que está en la posicion 5 del string.

* Si hago Insert(2,"z"), el hash nuevo es 8757 + ASCII("z"), ya que inserto la letra "z".

Este es un hash incremental, y la gracia es que en este caso se puede calcular en O(1) independiente del tamaño del string.
Si no lo hago incremental, entonces tendría que calcular el hash del string completo cada vez.

**Comment by mglambert** [comment]
Gracias, te pasaste!
