### ISSUE TITLE
Dudas Análisis Empírico

### ISSUE THREAD

**Issue by raiperez** [IIC2133-PUC/2017-1#84]
Hola.

Para el análisis empírico, qué se entiende por 'tasa de colisiones'? Fracción de inserciones en que hubo colisión?

Saludos

**Comment by alopez7** [comment]
Numero de colisiones al insertar / inserciones totales

Si al insertar un dato este colisiona más de una vez, se debe contar como colisión cada intento fallido.

**Comment by raiperez** [comment]
Perfecto, muchas gracias!

**Comment by raiperez** [comment]
@alopez7 Otra duda, con respecto al costo en inserción y búsqueda, solo contabilizamos el tiempo que usamos desde que ya tenemos el hash calculado hasta que terminamos de ubicar o encontrar la celda en cuestión, o me equivoco?

**Comment by Ghoeb** [comment]
Me parece bien que los quieras separar, pero asegurate de dejar en claro cuanto tiempo toma en calcular la función de hash (que debería ser más o menos siempre el mismo)

**Comment by alopez7** [comment]
Ambas métricas tienen sentido ya que miden cosas un poco distintas:
* Medir el tiempo con el hash ya calculado permite dimensionar que tan fácil es buscar o insertar en la tabla, lo que se relaciona directamente con que tan bien distribuyen los datos en tu tabla o que tan bien manejas las colisiones.
* Medir el tiempo incluyendo el cálculo del hash en cambio dimensiona la eficiencia de tu diccionario en general.

**Comment by javierlopeza** [comment]
Otra duda del análisis empírico: cuando el enunciado habla de 
> ... analizar cómo varía el desempeño al variar los siguientes parámetros:
**Tamaño de la tabla de hash (números primos, compuestos, potencias de 2, etc.)**...

Se refiere a que tenemos que implementar diferentes formas en que se expande el tamaño de la tabla de hash? En potencias de 2 me hace sentido, pero en número primos o compuestos no me queda tan claro. Al final, qué se espera de este análisis? Gracias!

**Comment by Ghoeb** [comment]
> Se refiere a que tenemos que implementar diferentes formas en que se expande el tamaño de la tabla de hash? 

No realmente, puedes siempre duplicar el tamaño de la tabla, pero de ahi buscar el número primo más cercano, o cosas así. Lo que importa es comparar como se comporta la tabla cuando su tamaño es siempre una potencia de 2, o es siempre un numero primo, etc.

**Comment by javierlopeza** [comment]
Cuando se expande la tabla de hash se tienen que rehashear las celdas: ¿consideramos estos rehasheos como inserciones (para la tasa de colisiones y el costo de inserción)? Porque al rehashear podrían haber nuevas colisiones.

**Comment by alopez7** [comment]
Cada vez que creas un largo de tabla nuevo empiezas a contar la cantidad de colisiones dado ese tamaño (contando los rehasheos). Lo que nos interesa el la cantidad de colisiones con el tamaño final.
