### ISSUE TITLE
Dudas Entropía

### ISSUE THREAD

**Issue by bjassael** [IIC2133-PUC/2017-1#85]
Hola, más o menos cuales son los valores de entropía esperados que debemos poder resolver para los puzzles?

**Comment by alopez7** [comment]
El puzzle tiene un grado de ramificación demasiado grande, no piensen que con una tabla de hash va a poder resolver el problema con muchos pasos.
La entropía hasta la cual debería resolver depende de muchos factores:
* Tamaño del tablero
* Cantidad de colores en el tablero
* Distribución inicial del tablero
* Etc...
Recomiendo mejor comparar el tiempo de su tarea sin usar una tabla y con tabla, eso es mucho más significativo.

**Comment by bjassael** [comment]
Buenas Gracias!
