### ISSUE TITLE
Problema al acceder a Cell *prev 

### ISSUE THREAD

**Issue by AndresSalcedo** [IIC2133-PUC/2017-1#87]
Hola, 

Al momento de setear una celda, guardo en ella algunas cosas, entre ellas el state del puzzle con metodo clone que viene implementado, mas o menos así: `celda.estado=puzzle_clone(state)`. En esta parte sí me imprime el puzzle. 
Al acceder al prev en el método `get cell`, para hacer la función incremental, no me imprime el puzzle. Accedo de esta manera: `prev->estado`
No estoy seguro qué estoy haciendo mal, agradezco comentarios.

**Comment by alopez7** [comment]
hay un caso en que prev es NULL, que es la primera vez que guardas algo en la tabla de hash. El primer estado no tiene estado anterior. En ese caso debes calcular el hash completo del estado, y no de manera incremental. Si no es eso, se tendría que analizar más en detalle.
