### ISSUE TITLE
Duda número máximo mpz

### ISSUE THREAD

**Issue by bmarinb** [IIC2133-PUC/2017-1#89]
Por lo que estaba viendo, el máximo valor que puedo almacenar en un dato mpz es 2^63 (¿o me equivoco?) , pero si quisiera una función inyectiva, necesito alcanzar hasta los 8^(64*64)  estados diferentes. ¿Cómo es esto posible?

**Comment by Ghoeb** [comment]
No no, es al reves, el máximo valor que puedes almacenar en un tipo básico, (uint64_t que es el más grande) es 2^64 - 1, es por eso que usamos MPZ, que no tiene limite de almacenamiento.

**Comment by bmarinb** [comment]
Entonces tengo un problema, estoy calculando las potencias de 8 para guardarlas en un arreglo
y a partir de la potencia 22 (2^3^22 = 2^66) imprime solo ceros, siendo que  la función mpz_get_ui debería retornar los dígitos menos significativos del número 
Este es el trozo de código que estoy usando
mpz_t* orden;
orden = malloc(sizeof(mpz_t)*h*w);
for (int i = 0; i < h*w; ++i)
{	
	mpz_init(orden[i]);
	mpz_ui_pow_ui(orden[i], 8, i);
	printf("%d, %lu\n",i,mpz_get_ui(orden[i]));
}
![image](https://user-images.githubusercontent.com/17581426/27210355-dc7fc204-521f-11e7-81f2-6f3feab302aa.png)

**Comment by Ghoeb** [comment]
Lo que lo está matando es eso que haces mpz_get_ui(orden[i]) para imprimir, osea, conviertes el numero guardado a tu tipo básico (muy probablemente uint64_t). Si el numero guardado en ese mpz es más grande que lo que cabe ahí, entonces muere y queda como cero.

MPZ tiene su propia funcion para imprimir numeros en consola, revisala en la sección I/O de la documentación.

**Comment by bmarinb** [comment]
Ok, gracias, probaré eso.De todas formas la documentación de la librería no lo deja claro.
Dice que si el número es más grande, se guardará la parte menos significativa, sin embargo, está guardando 0.
Function: unsigned long int mpz_get_ui (const mpz_t op)
Return the value of op as an unsigned long.

If op is too big to fit an unsigned long then just the least significant bits that do fit are returned. The sign of op is ignored, only the absolute value is used.

**Comment by Ghoeb** [comment]
Eso es porque cualquier potencia de 8, en binario, es un 1 seguido de muchos ceros.

**Comment by bmarinb** [comment]
Eso era 👍  gracias
