### ISSUE TITLE
Duda funciones de hash informe

### ISSUE THREAD

**Issue by AndresSalcedo** [IIC2133-PUC/2017-1#90]
Hola, 

En el enunciado indican que hay que hacer una función de hash incremental y una función de hash perfecta, y se pide que analicemos el desempeño de ambas y elijamos la mejor para que quede implementada en el código, pero yo hice una función de hash que es incremental y perfecta, y es una sola función de hash (la única división podría ser la primera vez que se calcula, que se computa el puzle completo, versus las siguientes veces que se computa de manera incremental)

No estoy seguro cómo debo realizar el análisis en el informe.

Gracias.

**Comment by Ghoeb** [comment]
La función perfecta tiene que pagar el precio de usar la librería de numeros grandes, lo que añade un tiempo significativo al programa. Deja esa funcion como tu función perfecta, e implementa una funcion incremental sencilla que pueda trabajar únicamente con tipos básicos (int, unsigned int, long, etc)

**Comment by AndresSalcedo** [comment]
Es decir las dos funciones que hay que analizar son una perfecta y una no perfecta, ambas incrementales? Creo que no queda claro en el enunciado, y tampoco que la diferencia radique en el uso de los long vs los mpz, por eso pregunto.

**Comment by Ghoeb** [comment]
No, la perfecta no tiene por que ser incremental, pero no hace daño si lo es. Y si, el uso de tipos basicos vs mpz si afecta, dado que las operaciones de tipos básicos están implementadas en hardware, mientras que las de mpz tienen un algoritmo (aunque esté escrito en assembly para hacerlo más rapido) para llevarlas a cabo. 

La idea de la tarea es que comparen el uso de una funcion rápida de calcular, vs una función perfecta  que por definición jamás generará colision de claves antes de insertarlas en la tabla (lo cual es una garantía importante)

Para la rápida les pedimos que sea incremental, y tiene sentido usar tipos básicos, pero es cierto que eso no lo exigimos en el enunciado :disappointed: 

Para la perfecta va a ser necesario usar una librería especial para manejar los números, y esos números pueden usar muchos bytes para ser guardados (1536 en el peor caso si interpretan el tablero como un numero en base 8). Eso, vs usar 8 bytes para un uint64_t, significa que los cálculos hechos con ese mpz deben ser AL MENOS 192 veces más lentos. 

¿Cual es la gracia de la función perfecta entonces? Que te ahorras la memoria de guardar el estado, y el tiempo de andar comparando estados para saber si estás en la celda correcta en la tabla de hash. 

¿Vale la pena? Esa es la idea de la tarea :whale:

**Comment by afcerna** [comment]
Existe algun inconveniente si implementé ambas funciones con la libreria GMP?

**Comment by Ghoeb** [comment]
No, en realidad no vamos a ponerles problema con eso, mientras signifiquen una mejora para el solver. 

@AndresSalcedo compara la perfecta incremental con la perfecta no incremental.

**Comment by Ghoeb** [comment]
@AndresSalcedo mejor dicho, usa mpz si quieres, pero n deberían ser la misma funcion, dado que van a distribuir exactamente igual

**Comment by AndresSalcedo** [comment]
@Ghoeb no quedé claro con el último mensaje. Puedo sólo comparar la perfecta incremental con la perfecta no incremental como dijiste? si se puede eso sería lo ideal, ya que me ahorraría bastante tiempo (que no tengo jaja). Van a distribuir igual, pero se van a poder apreciar las diferencias en tiempos de ejecución al integrar el tema incremental, o no hacerlo.
porfa?

**Comment by alopez7** [comment]
No puedes hacer eso porque perdería el sentido el análisis. Es evidente que la función perfecta incremental sería mejor. 
Debes crear una función incremental extra que funcione eficientemente en su cálculo. La idea de esto es que el costo de esa función radique en clonar el estado y en comparar estados.
