### ISSUE TITLE
Creacion de tablas con script

### ISSUE THREAD

**Issue by Togose** [IIC2133-PUC/2017-1#91]
Al usar el comando "./tabular.sh 1 4 4 4 'colisiones'"

Tengo este error:

![image](https://user-images.githubusercontent.com/6934191/27210972-303dede0-5224-11e7-9dd0-6af523aa8ae3.png)

No se si será un problema de mi código o si no entendí como se usa el script, cualquier ayuda sería muy útil. Gracias

**Comment by Ghoeb** [comment]
En que sistema operativo estás?

**Comment by Togose** [comment]
Estoy usando Bash de Ubuntu en Windows. Linux Subsystem
