### ISSUE TITLE
En qué momento debo crear las celdas y para qué sirve new_cell

### ISSUE THREAD

**Issue by bmarinb** [IIC2133-PUC/2017-1#92]
Llevo arrastrando esta duda un buen rato,
Si tal como dice el enunciado, creo las celdas en dictionary_get_cell ¿cómo verifico si la celda estaba inicialmente en el diccionario, si es que inicialmente en ese espacio no había una celda?
Si en cambio, podemos crear las celdas en dictionary_init, ¿podemos usar new_celll dentro de dictionary_get_cell para saber si la celda contiene un estado o es una celda sin valores?
¿new_cell es un atributo que nosotros tenemos la libertad de usar, o es un  atributo que se usa en el algoritmo de búsqueda y no debemos usarlo?

**Comment by AndresSalcedo** [comment]
No entiendo bien la primera duda, pero sobre lo de new cell, tento entendido que no puedes cambiar su estructura, pero si debes setearlo como TRUE al momento de insertar un valor en esa celda. 
Suerte en lo que queda!
